import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error("Could not find root element to mount to");
}

const root = ReactDOM.createRoot(rootElement);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// Register Service Worker for PWA (Standard Method)
// This avoids the 'virtual:pwa-register' module error in some environments
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    // Attempt to register the SW generated by the plugin
    navigator.serviceWorker.register('/sw.js').then(registration => {
      console.log('SW registered: ', registration);
    }).catch(registrationError => {
      // It's okay if this fails in dev mode without a full build
      console.log('SW registration failed (this is normal in dev mode if sw.js is not built): ', registrationError);
    });
  });
}